checkpoints:
  checkpoint_interval: 500
  checkpoints_path: /iopsstor/scratch/cscs/kponkshe/sb-decay/checkpoints/run_stable_openthoughts
  checkpoints_path_is_shared_file_system: true
  load_lr_scheduler: false
  load_optimizer: false
  resume_checkpoint_path: /iopsstor/scratch/cscs/kponkshe/sb-decay/ckpts/SmolLM3-3B/stage2-step-4200000/nanotron
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /iopsstor/scratch/cscs/kponkshe/sb-decay/text/data/openthoughts/processed/tokenized
      dataset_weights:
      - 1.0
      pad_samples_to_global_batch_size: false
      return_positions: true
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.2-1B
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 8
    seed: 6
  name: openthoughts_decay_stage3
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: smollm3-3B-custom-decay
  run: openthoughts-stage3-decay
  seed: 6
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 50
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 128000
    eos_token_id: 128001
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 2048
    initializer_range: 0.02
    intermediate_size: 11008
    is_qwen2_config: true
    max_position_embeddings: 4096
    moe_config: null
    num_attention_heads: 16
    num_hidden_layers: 36
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 2
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
    z_loss_coefficient: 1.0e-05
    z_loss_enabled: false
    no_rope_layer: 4
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0002
    lr_decay_starting_step: 1773
    lr_decay_steps: 1772
    lr_decay_style: linear
    lr_warmup_steps: 20
    lr_warmup_style: linear
    min_decay_lr: 0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params:
  - .*token_embedding.*
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 16
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: 4096
  tokenizer_name_or_path: /iopsstor/scratch/cscs/kponkshe/sb-decay/ckpts/SmolLM3-3B/stage2-step-4200000/hf
  tokenizer_revision: null
metrics_logging:
  log_level: 1
  log_detail_interval: 1000000000
tokens:
  batch_accumulation_per_replica: 36
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 1
  sequence_length: 4096
  train_steps: 1772
  val_check_interval: 100
lighteval: null
