# Model
model_name_or_path: /iopsstor/scratch/cscs/kponkshe/sb-decay/checkpoints/run_decay_dolma/hf
attn_implementation: flash_attention_2
dtype: bfloat16

# Dataset
dataset_name: open-thoughts/OpenThoughts2-1M
split: train
answer_only_loss: true
question_field: question
answer_field: answer
dataset_num_proc: 64
dataset_download_mode: reuse_dataset_if_exists
# dataset_cache_dir: /path/to/your/hf_datasets_cache
# offline: true

# Hyperparameters
learning_rate: 1.0e-4
gradient_checkpointing: false
num_train_epochs: 1.0
logging_steps: 10
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine
output_dir: /iopsstor/scratch/cscs/kponkshe/sb-decay/checkpoints/run_stable_dolma/hf/sft_openthoughts
report_to: wandb
seed: 42

# Checkpointing
checkpointing_steps: 500
save_total_limit: 3

# Hub
push_to_hub: false

# Finetuning mode
use_lora: false
